Fix regression in model code used by crash guilty processing
Some code in crash.py expects there to be a named parameter named 'id'
for get_new_crash_records(), but the method definition recently renamed
that parameter to '_id'. This was resulting in the following exception:

TypeError: get_new_crash_records() got an unexpected keyword argument
'id'

Signed-off-by: Patrick McCarty <patrick.mccarty@intel.com>